# Generated by Django 3.0.5 on 2020-04-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constituencytemplate',
            name='frequency',
        ),
        migrations.AlterField(
            model_name='constituencytemplate',
            name='examples',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailsentence',
            name='tree',
            field=models.TextField(blank=True, null=True),
        ),
    ]
