# Generated by Django 3.0.5 on 2020-05-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ngrams'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='annotated_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='manual_annotation_info',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='model_annotation_info',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='email',
            name='rules_annotation_info',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='emailsentence',
            name='annotated_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
